using Bgfx;
using System.Text.Json.Serialization;

namespace Staple
{
    [JsonConverter(typeof(JsonStringEnumConverter<TextureFlags>))]
    public enum TextureFlags: ulong
    {
		None = bgfx.TextureFlags.None,
		MSAASample = bgfx.TextureFlags.MsaaSample,
		RenderTarget = bgfx.TextureFlags.Rt,
		ComputeWrite = bgfx.TextureFlags.ComputeWrite,
		SRGB = bgfx.TextureFlags.Srgb,
		BlitDestination = bgfx.TextureFlags.BlitDst,
		ReadBack = bgfx.TextureFlags.ReadBack,
		RenderTargetMSAAX2 = bgfx.TextureFlags.RtMsaaX2,
		RenderTargetMSAAX4 = bgfx.TextureFlags.RtMsaaX4,
		RenderTargetMSAAX8 = bgfx.TextureFlags.RtMsaaX8,
		RenderTargetMSAAX16 = bgfx.TextureFlags.RtMsaaX16,
		RenderTargetMSAAShift = bgfx.TextureFlags.RtMsaaShift,
		RenderTargetMSAAMask = bgfx.TextureFlags.RtMsaaMask,
		RenderTargetWriteOnly = bgfx.TextureFlags.RtWriteOnly,
		RenderTargetShift = bgfx.TextureFlags.RtShift,
		RenderTargetMask = bgfx.TextureFlags.RtMask,
		SamplerUMirror = bgfx.SamplerFlags.UMirror,
		SamplerUClamp = bgfx.SamplerFlags.UClamp,
		SamplerUBorder = bgfx.SamplerFlags.UBorder,
		SamplerUShift = bgfx.SamplerFlags.UShift,
		SamplerUMask = bgfx.SamplerFlags.UMask,
		SamplerVMirror = bgfx.SamplerFlags.VMirror,
		SamplerVClamp = bgfx.SamplerFlags.VClamp,
		SamplerVBorder = bgfx.SamplerFlags.VBorder,
		SamplerVShift = bgfx.SamplerFlags.VShift,
		SamplerVMask = bgfx.SamplerFlags.VMask,
		SamplerWMirror = bgfx.SamplerFlags.WMirror,
		SamplerWClamp = bgfx.SamplerFlags.WClamp,
		SamplerWBorder = bgfx.SamplerFlags.WBorder,
		SamplerWShift = bgfx.SamplerFlags.WShift,
		SamplerWMask = bgfx.SamplerFlags.WMask,
		SamplerMinPoint = bgfx.SamplerFlags.MinPoint,
		SamplerMinAnisotropic = bgfx.SamplerFlags.MinAnisotropic,
		SamplerMinShift = bgfx.SamplerFlags.MinShift,
		SamplerMinMask = bgfx.SamplerFlags.MinMask,
		SamplerMagPoint = bgfx.SamplerFlags.MagPoint,
		SamplerMagAnisotropic = bgfx.SamplerFlags.MagAnisotropic,
		SamplerMagShift = bgfx.SamplerFlags.MagShift,
		SamplerMagMask = bgfx.SamplerFlags.MagMask,
		SamplerMipPoint = bgfx.SamplerFlags.MipPoint,
		SamplerMipShift = bgfx.SamplerFlags.MipShift,
		SamplerMipMask = bgfx.SamplerFlags.MipMask,
		SamplerCompareLess = bgfx.SamplerFlags.CompareLess,
		SamplerCompareLequal = bgfx.SamplerFlags.CompareLequal,
		SamplerCompareEqual = bgfx.SamplerFlags.CompareEqual,
		SamplerCompareGequal = bgfx.SamplerFlags.CompareGequal,
		SamplerCompareGreater = bgfx.SamplerFlags.CompareGreater,
		SamplerCompareNotequal = bgfx.SamplerFlags.CompareNotequal,
		SamplerCompareNever = bgfx.SamplerFlags.CompareNever,
		SamplerCompareAlways = bgfx.SamplerFlags.CompareAlways,
		SamplerCompareShift = bgfx.SamplerFlags.CompareShift,
		SamplerCompareMask = bgfx.SamplerFlags.CompareMask,
		SamplerBorderColorShift = bgfx.SamplerFlags.BorderColorShift,
		SamplerBorderColorMask = bgfx.SamplerFlags.BorderColorMask,
		SamplerReservedShift = bgfx.SamplerFlags.ReservedShift,
		SamplerReservedMask = bgfx.SamplerFlags.ReservedMask,
		SamplerSampleStencil = bgfx.SamplerFlags.SampleStencil,
		SamplerPoint = bgfx.SamplerFlags.Point,
		SamplerUvwMirror = bgfx.SamplerFlags.UvwMirror,
		SamplerUvwClamp = bgfx.SamplerFlags.UvwClamp,
		SamplerUvwBorder = bgfx.SamplerFlags.UvwBorder,
		SamplerBitsMask = bgfx.SamplerFlags.BitsMask,
	}
}
