<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
	<Reference Include="Newtonsoft.Json">
		<HintPath>..\..\Dependencies\JsonNet\Newtonsoft.Json.dll</HintPath>
	</Reference>
	<PackageReference Include="Microsoft.Build" Version="18.10.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Staple.Core\Staple.Core.csproj" />
    <ProjectReference Include="..\Staple.PackageManagement\Staple.PackageManagement.csproj" />
  </ItemGroup>

</Project>
